### ISSUE TITLE
fail to build with node 0.8.0 (mac)

### ISSUE THREAD

**Issue by rednaxus** [node-ffi/node-ffi#62]
libtool: link: ( cd ".libs" && rm -f "libffi_convenience.la" && ln -s "../libffi_convenience.la" "libffi_convenience.la" )
  TOUCH Release/obj.target/libffi.stamp.node
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
  CXX(target) Release/obj.target/ffi_bindings/src/callback_info.o
../src/callback_info.cc:68:3: error: no matching function for call to 'uv_unref'
  uv_unref(uv_default_loop());
  ^~~~~~~~
/Users/idan/.node-gyp/0.8.0/deps/uv/include/uv.h:252:16: note: candidate function not viable: no known conversion from 'uv_loop_t _' (aka 'uv_loop_s *') to 'uv_handle_t *'
      (aka 'uv_handle_s *') for 1st argument;
UV_EXTERN void uv_unref(uv_handle_t_);
               ^
1 error generated.
make: **\* [Release/obj.target/ffi_bindings/src/callback_info.o] Error 1
gyp ERR! rebuild error Error: `make` failed with exit code: 2
gyp ERR! rebuild error     at ChildProcess.onExit (/Users/idan/.nvm/v0.8.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:214:23)
gyp ERR! rebuild error     at ChildProcess.EventEmitter.emit (events.js:91:17)
gyp ERR! rebuild error     at Process._handle.onexit (child_process.js:674:10)
gyp ERR! not ok 
npm ERR! node-ffi@0.5.4 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the node-ffi@0.5.4 install script.
npm ERR! This is most likely a problem with the node-ffi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-ffi
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 11.4.0
npm ERR! command "/Users/idan/.nvm/v0.8.0/bin/node" "/Users/idan/.nvm/v0.8.0/bin/npm" "install" "node-ffi"
npm ERR! cwd /Users/idan/Documents/workspace/guestmob
npm ERR! node -v v0.8.0
npm ERR! npm -v 1.1.32
npm ERR! code ELIFECYCLE
npm ERR! message node-ffi@0.5.4 install: `node-gyp rebuild`
npm ERR! message `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/idan/Documents/workspace/guestmob/npm-debug.log
npm ERR! not ok code 0
