### ISSUE TITLE
Unable to rebuild with nw-gyp for Nodewebkit 0.11.6

### ISSUE THREAD

**Issue by sarangsapre** [node-ffi/node-ffi#197]
I was trying to build ffi for usage within nodeWebkit 0.11.6 and for Mac OSX 64 bit...ffi 1.3.0 was used.

Tried command : `nw-gyp clean configure --target=0.11.6 build --arch=ia32`

However, it failed to rebuild... Is it a ffi issue? 

```
 CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
In file included from ../src/ffi.cc:3:
In file included from ../src/ffi.h:18:
../node_modules/nan/nan.h:207:13: error: no type named 'SetCounterFunction' in 'v8::V8'
    v8::V8::SetCounterFunction(cb);
    ~~~~~~~~^
../node_modules/nan/nan.h:212:13: error: no type named 'SetCreateHistogramFunction' in 'v8::V8'
    v8::V8::SetCreateHistogramFunction(cb);
    ~~~~~~~~^
../node_modules/nan/nan.h:217:13: error: no type named 'SetAddHistogramSampleFunction' in 'v8::V8'
    v8::V8::SetAddHistogramSampleFunction(cb);
    ~~~~~~~~^
../node_modules/nan/nan.h:221:20: error: no member named 'IdleNotification' in 'v8::V8'
    return v8::V8::IdleNotification(idle_time_in_ms);
           ~~~~~~~~^
../node_modules/nan/nan.h:225:13: error: no member named 'LowMemoryNotification' in 'v8::V8'
    v8::V8::LowMemoryNotification();
    ~~~~~~~~^
../node_modules/nan/nan.h:229:13: error: no member named 'ContextDisposedNotification' in 'v8::V8'
    v8::V8::ContextDisposedNotification();
    ~~~~~~~~^
6 errors generated.
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/nw-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Darwin 12.5.0
gyp ERR! command "node" "/usr/local/bin/nw-gyp" "clean" "configure" "--target=0.11.6" "build" "--arch=x64"
gyp ERR! cwd /Users/sarangsapre/temp/smartamp_integration_nw11/plugins/node-ffi
gyp ERR! node -v v0.10.28
gyp ERR! nw-gyp -v v0.12.2
gyp ERR! not ok 
```

**Comment by unbornchikken** [comment]
You should use nw-js 0.12+.

**Comment by unbornchikken** [comment]
I'm closing this. If you have issues with NW.js 0.12, please open up an other issue. Thanks.
